// src/app/RootLayoutServer.tsx
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import layout from "./layout";
import RootLayoutClient from "./RootLayoutClient";

const font = Space_Grotesk({
  weight: ['300','400','500','600','700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-learning Website",
  description: "Generated by create next app",
};

export function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <RootLayoutServer>
      <RootLayoutClient>
        {children}
      </RootLayoutClient>
    </RootLayoutServer>
  );
}
